
#
# Makefile for the linux kernel.
#

obj-$(CONFIG_RX3000_BACKLIGHT)	+= rx3000_bl.o
obj-$(CONFIG_RX3000_BATTERY)	+= rx3000_battery.o
obj-$(CONFIG_RX3000_BLUETOOTH)	+= rx3000_bt.o
obj-$(CONFIG_RX3000_BUTTONS)	+= rx3000_buttons.o
obj-$(CONFIG_RX3000_SERIAL)	+= rx3000_serial.o
obj-$(CONFIG_RX3000_TS)		+= rx3000_ts.o
obj-$(CONFIG_RX3000_UDC)	+= rx3000_udc.o
