#
# Makefile for h1910/h1915 PDA support
#

obj-$(CONFIG_ARCH_H1900)		+= h1900.o h1900_pm.o h1900_ssp.o h1900_irda.o h1900_udc.o
obj-$(CONFIG_IPAQ_H1900_BUTTONS)	+= h1900_buttons.o
obj-$(CONFIG_IPAQ_H1900_LCD)		+= h1900_lcd.o h1900_bl.o
