#
# Makefile for Palm LifeDrive support
#

obj-$(CONFIG_MACH_HTCAPACHE)        += htcapache.o
obj-$(CONFIG_MACH_HTCAPACHE)        += htcapache-bl.o
obj-$(CONFIG_MACH_HTCAPACHE)        += htcapache-mc.o
obj-$(CONFIG_MACH_HTCAPACHE)        += htcapache-leds.o
obj-$(CONFIG_MACH_HTCAPACHE)        += htcapache-frontkeys.o
obj-$(CONFIG_MACH_HTCAPACHE)        += htcapache-pm.o
