#
# Dell Axim X5 PDA Makefile for the linux kernel.
#

obj-$(CONFIG_ARCH_AXIMX5)	+= aximx5.o
obj-$(CONFIG_AXIMX5_MISC)	+= aximx5_misc.o
obj-$(CONFIG_AXIMX5_LCD)	+= aximx5_lcd.o
obj-$(CONFIG_AXIMX5_BACKLIGHT)	+= aximx5_bl.o
obj-$(CONFIG_AXIMX5_PCMCIA)	+= aximx5_pcmcia.o
obj-$(CONFIG_AXIMX5_AC97)	+= aximx5_ac97.o
obj-$(CONFIG_AXIMX5_BUTTONS)	+= aximx5_buttons.o
