#h3900 support

obj-$(CONFIG_MACH_H3900)        += h3900.o h3900_pm.o
obj-$(CONFIG_IPAQ_H3900_LCD)	+= h3900_lcd.o
obj-$(CONFIG_IPAQ_H3900_BACKLIGHT) += h3900_bl.o
obj-$(CONFIG_IPAQ_H3900_BATTERY) += h3900_battery.o
