#
# HTC Magician Makefile
#
obj-$(CONFIG_MACH_MAGICIAN)		+= magician.o
obj-$(CONFIG_MAGICIAN_PM)		+= magician_pm.o
obj-$(CONFIG_MAGICIAN_LCD)		+= magician_lcd.o
obj-$(CONFIG_MAGICIAN_TS)		+= magician_ts.o
obj-$(CONFIG_MAGICIAN_PHONE)		+= magician_phone.o
