#
## Palm TX Linux kernel Makefile
#
#
obj-$(CONFIG_MACH_XSCALE_PALMTX) 	+= palmtx.o
obj-$(CONFIG_PALMTX_BATTERY)		+= palmtx_battery.o
obj-$(CONFIG_PALMTX_PM)			+= palmtx_pm.o
obj-$(CONFIG_PALMTX_PCMCIA)      	+= palmtx_pcmcia.o
obj-$(CONFIG_PALMTX_BORDER)             += palmtx_border.o
