#
# Palm Tungsten|T3 Linux kernel Makefile
#

obj-$(CONFIG_MACH_T3XSCALE)		+= palmtt3.o
obj-$(CONFIG_PALMTT3_BUTTONS)		+= palmtt3_buttons.o
obj-$(CONFIG_PALMTT3_BATTERY)		+= palmtt3_battery.o
obj-$(CONFIG_PALMTT3_BLUETOOTH)		+= palmtt3_bt.o
obj-$(CONFIG_PALMTT3_FBKEYBOARD)	+= palmtt3_fbkeyb.o