# Asus 730 Makefile

obj-$(CONFIG_MACH_A730)        += a730.o a730_pm.o a730_bl.o a730_lcd.o a730_buttons.o a730_pcmcia.o a730_mmc.o a730_usb.o a730_udc.o
#obj-$(CONFIG_CPU_FREQ_PXA)    += a730_voltage.o
obj-m				+= a730_bt.o
obj-m				+= a730_flash.o
obj-$(CONFIG_ASUS730_WM9712)	+= a730_ac97.o
