#
# Makefile for light-weight ADC drivers.
#

obj-$(CONFIG_ADC)		+= adc.o
obj-$(CONFIG_ADC_ADS7846_SSP)        += ads7846_adc_ssp.o
obj-$(CONFIG_ADC_TSC2200_SSP)        += tsc2200_adc_ssp.o
obj-$(CONFIG_ADC_AD7877)	+= ad7877.o
obj-$(CONFIG_ADC_ASIC2)		+= asic2_adc.o
obj-$(CONFIG_ADC_SAMCOP)	+= samcop_adc.o
