#
# Makefile for HTC Sable
#
obj-$(CONFIG_MACH_HW6900)        += htcsable.o htcsable_udc.o \
                                    htcsable_ts2.o \
                                    htcsable_pm.o \
                                    htcsable_core.o \
				    htcsable_keyboard.o \
                                    htcsable_buttons.o \
                                    htcsable_kbd.o \
                                    htcsable_bt.o htcsable_phone.o \
				    htcsable_rom.o

obj-$(CONFIG_HTCSABLE_LCD)       += htcsable_lcd.o
obj-$(CONFIG_HTCSABLE_BACKLIGHT)       += htcsable_bl.o

