# h5400 support

CPPFLAGS += -I$(TOPDIR)/arch/arm/common/ipaq

obj-$(CONFIG_ARCH_H5400)	+= h5400.o
obj-$(CONFIG_IPAQ_H5400_BT)	+= h5400_bt.o
obj-$(CONFIG_IPAQ_H5400_LCD)	+= h5400_lcd.o
obj-$(CONFIG_IPAQ_H5400_BL)	+= h5400_bl.o
obj-$(CONFIG_IPAQ_H5400_WIFI)	+= h5400_wifi.o
obj-$(CONFIG_IPAQ_H5400_AUDIO)	+= h5400_audio.o
