# Backlight & LCD drivers

obj-$(CONFIG_LCD_CLASS_DEVICE)		+= lcd.o
obj-$(CONFIG_BACKLIGHT_CLASS_DEVICE)	+= backlight.o
obj-$(CONFIG_BACKLIGHT_CORGI)		+= corgi_bl.o
obj-$(CONFIG_BACKLIGHT_HP680)		+= hp680_bl.o
obj-$(CONFIG_BACKLIGHT_LOCOMO)		+= locomolcd.o
obj-$(CONFIG_BACKLIGHT_PROGEAR)		+= progear_bl.o
obj-$(CONFIG_BACKLIGHT_HX2750)		+= hx2750_bl.o
obj-$(CONFIG_BACKLIGHT_H2200)		+= h2200_bl.o
obj-$(CONFIG_LCD_H2200)			+= h2200_lcd.o
obj-$(CONFIG_BACKLIGHT_S3C2410)		+= s3c2410_lcd.o

