#
# Dell Axim PDA Makefile for the linux kernel.
#
#obj-$(CONFIG_MACH_X30)         += aximx30_core_minimal.o
obj-$(CONFIG_MACH_X30)		+= aximx30.o 
obj-$(CONFIG_X30_CORE)		+= aximx30_core.o
obj-$(CONFIG_AXIMX30_LCD)	+= aximx30_lcd.o

