#
# Makefile for HTC Athena
#

obj-$(CONFIG_MACH_HTCATHENA)		+= htcathena.o
obj-$(CONFIG_HTCATHENA_CPLD1)		+= htcathena_cpld1.o
obj-$(CONFIG_HTCATHENA_CPLD2)		+= htcathena_cpld2.o
#obj-$(CONFIG_HTCATHENA_PHONE)		+= htcathena_phone.o
obj-$(CONFIG_HTCATHENA_VSFB)		+= htcathena_vsfb.o
