
# LED Core
obj-$(CONFIG_NEW_LEDS)			+= led-core.o
obj-$(CONFIG_LEDS_CLASS)		+= led-class.o
obj-$(CONFIG_LEDS_TRIGGERS)		+= led-triggers.o

# LED Platform Drivers
obj-$(CONFIG_LEDS_CORGI)		+= leds-corgi.o
obj-$(CONFIG_LEDS_LOCOMO)		+= leds-locomo.o
obj-$(CONFIG_LEDS_SPITZ)		+= leds-spitz.o
obj-$(CONFIG_LEDS_IXP4XX)		+= leds-ixp4xx-gpio.o
obj-$(CONFIG_LEDS_TOSA)			+= leds-tosa.o
obj-$(CONFIG_LEDS_S3C24XX)		+= leds-s3c24xx.o
obj-$(CONFIG_LEDS_AMS_DELTA)		+= leds-ams-delta.o
obj-$(CONFIG_LEDS_NET48XX)		+= leds-net48xx.o
obj-$(CONFIG_LEDS_WRAP)			+= leds-wrap.o
obj-$(CONFIG_LEDS_H1940)		+= leds-h1940.o
obj-$(CONFIG_LEDS_COBALT)		+= leds-cobalt.o
# Handhelds.org drivers
obj-$(CONFIG_LEDS_MAGICIAN)		+= leds-magician.o
obj-$(CONFIG_LEDS_ASIC3)		+= leds-asic3.o
obj-$(CONFIG_LEDS_PASIC3)		+= leds-pasic3.o
obj-$(CONFIG_LEDS_SAMCOP)		+= leds-samcop.o
obj-$(CONFIG_LEDS_HAMCOP)		+= leds-hamcop.o
obj-$(CONFIG_LEDS_GHI270)		+= leds-ghi270.o

# Hack&Dev drivers
obj-$(CONFIG_LEDS_PALMLD)             += leds-palmld.o
obj-$(CONFIG_LEDS_PALMTT3)            += leds-palmtt3.o
obj-$(CONFIG_LEDS_PALMZ72)            += led-palmz72.o
obj-$(CONFIG_LEDS_PALMT650)           += leds-palmt650.o
obj-$(CONFIG_LEDS_PALMT680)           += leds-palmt680.o


# LED Triggers
obj-$(CONFIG_LEDS_TRIGGER_TIMER)	+= ledtrig-timer.o
obj-$(CONFIG_LEDS_TRIGGER_HWTIMER)	+= ledtrig-hwtimer.o
obj-$(CONFIG_LEDS_TRIGGER_IDE_DISK)	+= ledtrig-ide-disk.o
obj-$(CONFIG_LEDS_TRIGGER_BACKLIGHT)	+= ledtrig-backlight.o
obj-$(CONFIG_LEDS_TRIGGER_HEARTBEAT)	+= ledtrig-heartbeat.o
obj-$(CONFIG_LEDS_TRIGGER_SHARED)	+= ledtrig-shared.o
obj-$(CONFIG_LEDS_TRIGGER_MMC_CARD)	+= ledtrig-mmc-card.o
