# Asus 620 Makefile

CFLAGS += -Idrivers/pcmcia

obj-$(CONFIG_MACH_A620)         += asus620.o asus620_gpo.o
obj-$(CONFIG_A620_LCD)          += asus620_lcd.o
obj-$(CONFIG_A620_TS)       	+= asus620_ts.o
obj-$(CONFIG_A620_BUTTONS)      += asus620_buttons.o
obj-$(CONFIG_A620_PCMCIA)       += asus620_pcmcia.o
obj-$(CONFIG_A620_FLASHFAKE)    += asus620_flashfake.o
