#
# Makefile for Palm LifeDrive support
#

obj-$(CONFIG_MACH_XSCALE_PALMLD)        += palmld.o
obj-$(CONFIG_PALMLD_PCMCIA)		+= palmld_pcmcia.o 
obj-$(CONFIG_PALMLD_IDE)		+= palmld_ide.o
obj-$(CONFIG_PALMLD_PM)			+= palmld_pm.o
