#
# Makefile for Palm LifeDrive support
#

obj-$(CONFIG_MACH_XSCALE_PALMLD)        += palmld.o
obj-$(CONFIG_PALMLD_PCMCIA)		+= palmld_pcmcia.o 
obj-$(CONFIG_PALMLD_USB)		+= palmld_usb.o 
obj-$(CONFIG_PALMLD_IDE)		+= palmld_ide.o
obj-$(CONFIG_PALMLD_PM)			+= palmld_pm.o
obj-$(CONFIG_PALMLD_BATTERY)		+= palmld_battery.o
obj-$(CONFIG_PALMLD_BORDER)		+= palmld_border.o
