#
# Makefile for Palm Zire 31 support
#

obj-$(CONFIG_MACH_ZIRE31) 	+= palmz31.o
obj-$(CONFIG_PALMZ31_BUTTONS)	+= palmz31_buttons.o 
obj-$(CONFIG_GPIOED)		+= gpioed.o
obj-$(CONFIG_GPIOEDNG)		+= gpioed-ng.o
