#
# Makefile for Blueangel PDA support
#

obj-$(CONFIG_MACH_BLUEANGEL)         += blueangel.o
obj-$(CONFIG_MACH_BLUEANGEL)         += blueangel_tsc2200.o
obj-$(CONFIG_MACH_BLUEANGEL_LCD)     += blueangel_lcd.o
obj-$(CONFIG_MACH_BLUEANGEL_DS1WM)   += blueangel_ds1wm.o
obj-$(CONFIG_MACH_BLUEANGEL_BACKLIGHT) += blueangel_bl.o
obj-$(CONFIG_MACH_BLUEANGEL_PCMCIA)  += blueangel_pcmcia.o
obj-$(CONFIG_MACH_BLUEANGEL_SUSPEND) += blueangel_suspend.o
obj-$(CONFIG_MACH_BLUEANGEL_LEDS)    += blueangel_leds.o
obj-$(CONFIG_MACH_BLUEANGEL_KEYPAD)  += blueangel_kp.o
obj-$(CONFIG_MACH_BLUEANGEL_POWER)   += blueangel_power.o
obj-$(CONFIG_MACH_BLUEANGEL_ROM)     += blueangel_rom.o
obj-$(CONFIG_MACH_BLUEANGEL_DPRAM)   += blueangel_dpram.o
obj-$(CONFIG_MACH_BLUEANGEL_PHONE)   += blueangel_phone.o
obj-$(CONFIG_MACH_BLUEANGEL_BLUETOOTH)  += blueangel_bt.o
obj-$(CONFIG_MACH_BLUEANGEL_SERIAL)  += blueangel_serial.o
