#
# HP iPAQ hx4700 Linux kernel Makefile
#

obj-$(CONFIG_MACH_H4700)	+= hx4700.o hx4700_bl.o
obj-$(CONFIG_HX4700_CORE)	+= hx4700_core.o
obj-$(CONFIG_HX4700_POWER2)	+= hx4700_power2.o
obj-$(CONFIG_HX4700_NAVPOINT)	+= hx4700_navpt.o
obj-$(CONFIG_HX4700_PCMCIA) 	+= hx4700_pcmcia.o
obj-$(CONFIG_HX4700_LCD) 	+= hx4700_lcd.o
obj-$(CONFIG_HX4700_BLUETOOTH) 	+= hx4700_bt.o
