# arch/arm/mach-s3c2442/Makefile
#
# Copyright 2007 Simtec Electronics
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

obj-$(CONFIG_CPU_S3C2442)	+= s3c2442.o
obj-$(CONFIG_CPU_S3C2442)	+= clock.o

# Machine support

obj-$(CONFIG_MACH_RX1950)	+= mach-rx1950.o
obj-$(CONFIG_MACH_HTCHERMES)	+= htchermes/
obj-$(CONFIG_MACH_HTC_TRINITY)	+= htctrinity/
