#
# Palm Tungsten C Linux kernel Makefile
#

obj-$(CONFIG_MACH_OMAP_PALMTC)		+= palmtc.o
obj-$(CONFIG_PALMTC_KEYBOARD)		+= palmtc_keyboard.o
obj-$(CONFIG_PALMTC_AC97)		+= palmtc_ac97.o
obj-$(CONFIG_PALMTC_UCB1400)		+= ptc_ucb1400.o
obj-$(CONFIG_PALMTC_PCMCIA)		+= palmtc_pcmcia.o
