# Makefile for mq200 video driver
# 4 Aug 2003, Holger Hans Peter Freyther
#

obj-$(CONFIG_FB_MQ200)           += mq_skeleton.o mq_external.o
obj-$(CONFIG_FB_MQ200_BACKLIGHT) += simpad_bl.o
obj-$(CONFIG_FB_MQ200_LCD)       += simpad_lcd.o

