#
# Makefile for h4000 PDA support
#

obj-$(CONFIG_MACH_H4000)         += h4000.o h4000_pm.o
obj-$(CONFIG_IPAQ_H4000_LCD)     += h4000_lcd.o
obj-$(CONFIG_IPAQ_H4000_PCMCIA)  += h4000_pcmcia.o
obj-$(CONFIG_IPAQ_H4000_BT)      += h4000_bt.o
obj-$(CONFIG_IPAQ_H4300_KBD)     += h4300_kbd.o
