#
# Rover PDA Makefile for the linux kernel.
#

obj-$(CONFIG_ARCH_ROVERP1) 	+= roverp1.o
obj-$(CONFIG_ROVERP1_LCD)	+= roverp1_lcd.o
obj-$(CONFIG_ARCH_ROVERP5P) 	+= roverp5p.o
obj-$(CONFIG_ROVERP5P_LCD)	+= roverp5p_lcd.o
obj-$(CONFIG_ROVERP5P_PCMCIA)	+= roverp5p_pcmcia.o

