# Asus MyPal A716 Makefile

obj-$(CONFIG_MACH_A716)         += a716.o a716_gpo.o a716_buttons.o a716_ssp.o a716_pm.o a716_lcd.o a716_bl.o
obj-$(CONFIG_MACH_A716)         += a716_bt.o a716_irda.o a716_mci.o a716_pm.o a716_udc.o
obj-$(CONFIG_A716_PCMCIA)       += a716_pcmcia.o
