#
# Makefile for HTC Universal
#

snd-htcuniversal-ak4641-objs := htcuniversal_ak4641.o

obj-$(CONFIG_MACH_HTCUNIVERSAL)		+= htcuniversal.o htcuniversal_pm.o
obj-$(CONFIG_HTCUNIVERSAL_CORE)		+= htcuniversal_core.o
obj-$(CONFIG_HTCUNIVERSAL_POWER)	+= htcuniversal_power2.o
obj-$(CONFIG_HTCUNIVERSAL_LCD)		+= htcuniversal_lcd.o
obj-$(CONFIG_HTCUNIVERSAL_BACKLIGHT)	+= htcuniversal_bl.o
obj-$(CONFIG_HTCUNIVERSAL_TS2)		+= htcuniversal_ts2.o
obj-$(CONFIG_HTCUNIVERSAL_BUTTONS) 	+= htcuniversal_buttons.o
obj-$(CONFIG_HTCUNIVERSAL_BLUETOOTH)	+= htcuniversal_bt.o 
obj-$(CONFIG_HTCUNIVERSAL_PHONE)	+= htcuniversal_phone.o 
obj-$(CONFIG_HTCUNIVERSAL_UDC)		+= htcuniversal_udc.o

obj-$(CONFIG_HTCUNIVERSAL_AK4641)	+= htcuniversal_ak4641.o
